### PR TITLE
Add Karazhan icons

### PR DESCRIPTION
**Pull request by ErikJson**
I went ahead and created the icons for Karazhan. I'm not super happy with the result as they differ a bit from the others, but when rendered they look ok. Feel free to take it or leave it :)

Please note that I'm not sure what minifying method you are using, so I just used the first online tool I found on Google. If this is an issue you can let me know how you do it and I'll make an update.

### CODE REVIEW

**Comment by jleclanche** [comment]
Landed in 4b469649e6746873df055f8ddfa6f8a631f28438. Thank you!

**Comment by ErikJson** [comment]
@jleclanche I just noticed that the minimized file in the repo wasn't updated?

**Comment by jleclanche** [comment]
@knugen yeah, we're setting up a cdn and a jenkins job to autoupdate it outside of the repository. Stay tuned.

**Comment by ErikJson** [comment]
Ok great! My follow-up question would have been if there was a plan for automating it :)

**Pull request closed without merging**
